/**
 * Shared validation options for form dropdowns.
 *
 * Local demo source: Google Sheet "Forms Fields Validations", tab "Location".
 * Live target: replace/sync this source from Supabase or a secured backend sync
 * from the Google Sheet, then keep form imports unchanged.
 */
export const LOCATIONS = [
  'Commissary-KHI',
  'Events/ Off-site Carts-KHI',
  'Karachi Club',
  'KDA/Tipu-D43',
  'KHI-DHA-P8',
  'Malir',
  'Back Office-KHI',
  'Commissary-LHR',
  'Events/ Off-site Carts- LHR',
  'Back Office- LHR',
  'LHR-DHA-P6',
];

export const PAYMENT_LOCATIONS = [
  ...LOCATIONS,
  'Fatani Estate',
  'Personal',
];

export const BANK_NAMES = [
  'Albaraka',
  'Allied Bank',
  'Apna Bank',
  'Askari Bank',
  'Bank Al Falah',
  'Bank Al Habib',
  'Bank Islami',
  'Bank Of Punjab',
  'Burj Bank',
  'DIB',
  'Easypaisa',
  'Faysal Bank',
  'Habib Metropolitan Ltd',
  'HBL',
  'JS Bank',
  'KASB Bank',
  'Meezan Bank',
  'Micro Finance Ubank',
  'Muslim Commercial Bank',
  'Sadapay',
  'Samba Bank',
  'SCB',
  'Silk Bank',
  'Sind Bank',
  'Soneri Bank Limited',
  'Summit Bank',
  'Nayapay',
  'Tameer Bank',
  'UBL',
  'FINCA Pay',
  'Jazz Cash',
  'Others or n/a',
];

export const LUNA_BANKS = [
  'HBL - 2203',
  'AL-Habib- 3601',
  'Faysal- 3867',
  'Al-Falah- 0598',
  'Faysal- 3928-F&C',
  'Al-Falah- F&C',
  'Cash-Back Office-KHI',
  'Cash-Branch-DHA-P8',
  'Cash-Branch-KDA/Tipu-D43',
  'Cash-Branch-Commissary-KHI',
  'Add option',
];

export const PAYMENT_CATEGORIES = [
  'Advertisement',
  'Bank Charges',
  'Beverages',
  'Capital Work',
  'Cash Purchase',
  'Courier',
  'Delivery Charges',
  'Electricity Expense',
  'Fuel',
  'Gas Expense',
  'Insurance',
  'Internet',
  'Maintenance',
  'Marketing',
  'Medical',
  'Office Expense',
  'Packaging',
  'Payroll',
  'Petty Cash',
  'Professional Fee',
  'Rent',
  'Repair and Maintenance',
  'Salary',
  'Security',
  'Software',
  'Staff Meal',
  'Tax Payment',
  'Tea / Coffee',
  'Transport',
  'Utilities',
  'Vendor Payment',
  'Other',
];

export const VENDOR_NAMES = [
  'A&A Traders',
  'Achha Foods (Pvt.) Ltd.',
  'Afil Industries',
  'AL- Momin Enterprises',
  'Al-Wasay',
  'Americom Technologies (Pvt.) Ltd.',
  'Apex Packages (SMC-Private) Ltd.',
  'Asif Brother CD',
  'Asif Brothers CD',
  'At- Tahur Ltd.',
  'AT-Tahur Limited',
  'Axiom International Trading',
  'Bennys By Benedition',
  'Big Bird Foods Ltd',
  'Bismillah Electronics',
  'Bismillah Special Sabzi Suppliers',
  'Bismillah Special Sabzi Supply',
  'BK Enterprises',
  'Brenqo',
  'Cafe And Beverages Lab',
  'Corporate Chef And Co',
  'Gamco Agencies',
  'Haaniya International',
  'Hilltop Enterprise',
  'Horeca Mondo',
  'Horeca Systems',
  'International Brands Distributions',
  'Irshad Brothers Gas Agency',
  'Khurram Enterprises',
  'M.I.A Holidays',
  'Maple Star Food Solutions',
  'Markhor Now',
  'Mirwan (Market At Spring)',
  'Muhammad Fahad Aslam',
  'Muhammad Wasi',
  'Multiple Trading',
  'MYD Ventures (Pvt.) Ltd.',
  'Nur Enterprises',
  'Opal Distributor (Pvt.) Ltd.',
  'Orish Foods (Pvt.) Ltd.',
  'Ozone Enterprises',
  'Printeze',
  'Pura Springs (Pvt.) Ltd.',
  'Raim Enterprises',
  'Salsabakes',
  'SH Traders',
  'Sharif Milk Products (Pvt.) Ltd.',
  'Sheheryar Enterprises',
  'Smores',
  'Swiss Packaging',
  'The Vittles Company',
  'Trade Distributor',
  'Tradsol',
  'TZ Marketing',
  'Umer Traders',
  'Usman Brothers (Pvt.) Ltd.',
  'Venus Food Services Ltd.',
  'Wild Flour Bakery',
  'Add New Vendor',
];

export const APPROVED_VENDOR_NAMES = VENDOR_NAMES.filter((name) => name !== 'Add New Vendor');
